SPANISH_AIRPORTS = {
    "LECO": "A Coruña",
    "LEAB": "Albacete",
    "LEAL": "Alicante-Elche",
    "LEAM": "Almería",
    "LESU": "Andorra-La Seu d'Urgell",
    "LEAS": "Asturias",
    "LEBZ": "Badajoz/Talavera la Real",
    "LEBL": "Barcelona/El Prat",
    "LEBB": "Bilbao",
    "LEBG": "Burgos",
    "LECH": "Castellón",
    "LEBA": "Córdoba",
    "GCFV": "Fuerteventura",
    "LEGE": "Girona",
    "GCLP": "Gran Canaria",
    "LEGR": "Granada/Federico García Lorca",
    "GCHI": "Hierro",
    "LEHC": "Huesca",
    "LEIB": "Ibiza",
    "LEJR": "Jerez",
    "GCGM": "La Gomera",
    "GCLA": "La Palma",
    "GCRR": "Lanzarote",
    "LELN": "León",
    "LEDA": "Lleida",
    "LERJ": "Logroño",
    "LEMD": "Madrid/Adolfo Suárez Madrid-Barajas",
    "LECU": "Madrid/Cuatro Vientos",
    "LEMG": "Málaga/Costa del Sol",
    "GEML": "Melilla",
    "LEMH": "Menorca",
    "LEMI": "Murcia/Región de Murcia",
    "LEPA": "Palma de Mallorca",
    "LEPP": "Pamplona",
    "LERS": "Reus",
    "LELL": "Sabadell",
    "LESA": "Salamanca",
    "LESO": "San Sebastián",
    "LEXJ": "Santander/Seve Ballesteros",
    "LEST": "Santiago",
    "LEZL": "Sevilla",
    "GCXO": "Tenerife Norte",
    "GCTS": "Tenerife Sur",
    "LEVC": "Valencia/Manises",
    "LEVD": "Valladolid/Villanubla",
    "LEVX": "Vigo",
    "LEVT": "Vitoria",
    "LEZG": "Zaragoza",
    "LEAG": "Algeciras (Helipuerto)",
    "GECE": "Ceuta (Helipuerto)",
    "LESB": "Mallorca/Son Bonet",
    "LETL": "Teruel",
    # International fallbacks
    "LFPG": "París-Charles de Gaulle",
    "EGLL": "Londres Heathrow",
    "KJFK": "Nueva York JFK",
    "EDDF": "Frankfurt",
}